sudo: required
services:
    - docker

before_install:
    - docker build -t chanmheric/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true chanmheric/react-test npm test

after_success:
    - docker build -t chanmheric/multi-client ./client
    - docker build -t chanmheric/multi-nginx ./nginx
    - docker build -t chanmheric/multi-server ./server
    - docker build -t chanmheric/multi-worker ./worker

    # Log in
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push chanmheric/multi-client
    - docker push chanmheric/multi-nginx
    - docker push chanmheric/multi-server
    - docker push chanmheric/multi-worker 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-557732472408
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

